### ISSUE TITLE
Convenience method for reading booleans

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/Pdoxcl2Sharp#12]
`parser.ReadBool()` should be a method that is implemented so that clients don't have to memorize that "yes" means true and "no" means false

Especially since the writers have methods that write out boolean values.

**Comment by Zarathos** [comment]
The parser fails to parse a rare occurrence of "1" or "0" booleans. The variable "growth_state" can be either "0" or "1" expressing "false" or "true" but the "0" value is not being taken into account and when writing data back it's probably marked as "no" or "yes" depending on the value.

**Comment by nickbabcock** [comment]
You're 100% right. I think you'll have to leave growth_state as a string/number and interpret it higher up, unfortunately.
