### ISSUE TITLE
Consecutive Elements with ID

### ISSUE THREAD

**Issue by Zarathos** [nickbabcock/Pdoxcl2Sharp#32]
Dear nickbabcock, I recently started tinkering a little bit your parser to fix some issues on my Stellaris savegames. It works like a charm, but I think it cannot handle this kind of parsing:

```
pop=
{
	0={
		species_index=120
		growth_state=1
		ethos={
			ethic="ethic_individualist"
			ethic="ethic_fanatic_materialist"
		}
		tile=844437815033858		pop_faction=0
		required_growth={
			type=food_surplus
			value=25.000
		}
	}
	1={
		species_index=120
		growth_state=1
		ethos={
			ethic="ethic_individualist"
			ethic="ethic_fanatic_materialist"
		}
		tile=1125912791744514		pop_faction=0
		required_growth={
			type=food_surplus
			value=25.000
		}
	}
	2={
		species_index=120
		growth_state=1
		ethos={
			ethic="ethic_individualist"
			ethic="ethic_fanatic_materialist"
		}
		tile=844433520066562		pop_faction=0
		required_growth={
			type=food_surplus
			value=25.000
		}
	}
}
```

Where the number before the brakets is a unique identifier. Do you have any plan on improving this for the new synthax being used? Best regards.

**Comment by nickbabcock** [comment]
In EU4 savegames, provinces are stored like so

```
-1={
  name="Stockholm"
  # etc
}
-2={
  name="Another one"
  # etc
}
```

This was solved in [ProvinceCollection.cs](https://github.com/nickbabcock/EU4.Savegame/blob/7f1b81fabc7a584cb675512d5112b4cd770a6c2a/EU4.Savegame/ProvinceCollection.cs#L54-L57)

```csharp
public void TokenCallback(ParadoxParser parser, string token)
{
    provinces.Add(parser.Parse(new Province(-int.Parse(token))));
}
```

Let me know if this helps.

**Comment by Zarathos** [comment]
Aaaaah that works like a charm! Many thanks man!

**Comment by nickbabcock** [comment]
No problem, I haven't tested this parser with Stellaris or for HOI4, so if you come across bugs or if you have improvements you've coded, feel free to file more issues/PRs :smile:
